package org.broadinstitute.hellbender.tools.copynumber.formats.collections;

import org.broadinstitute.hellbender.exceptions.UserException;
import org.broadinstitute.hellbender.tools.copynumber.formats.metadata.SampleLocatableMetadata;
import org.broadinstitute.hellbender.tools.copynumber.formats.records.LinearNonLocatableCopyRatio;
import org.broadinstitute.hellbender.tools.copynumber.formats.records.DenoisedLocatableCopyRatio;
import org.broadinstitute.hellbender.utils.SimpleInterval;
import org.broadinstitute.hellbender.utils.tsv.DataLine;
import org.broadinstitute.hellbender.utils.tsv.TableColumnCollection;
import org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller;
import org.broadinstitute.hellbender.tools.copynumber.PostprocessGermlineCNVCalls;

import java.io.File;
import java.util.List;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * Collection of denoised copy ratios generated by {@link GermlineCNVCaller} with their corresponding intervals
 *
 * @author Andrey Smirnov &lt;asmirnov@broadinstitute.org&gt;
 */
public class DenoisedLocatableCopyRatioCollection extends AbstractSampleLocatableCollection<DenoisedLocatableCopyRatio> {

    enum DenoisedLocatableCopyRatioTableColumn {
        CONTIG,
        START,
        END,
        DENOISED_COPY_RATIO;

        static final TableColumnCollection COLUMNS = new TableColumnCollection((Object[]) values());
    }

    public DenoisedLocatableCopyRatioCollection(final File inputFile) {
        super(inputFile, DenoisedLocatableCopyRatioTableColumn.COLUMNS,
                getDenoisedLocatableCopyRatioRecordFromDataLineDecoder(),
                getDenoisedLocatableCopyRatioRecordToDataLineEncoder());
    }

    public DenoisedLocatableCopyRatioCollection(final SampleLocatableMetadata metadata,
                                                final List<DenoisedLocatableCopyRatio> denoisedLocatableCopyRatioList) {
        super(metadata, denoisedLocatableCopyRatioList, DenoisedLocatableCopyRatioTableColumn.COLUMNS,
                getDenoisedLocatableCopyRatioRecordFromDataLineDecoder(),
                getDenoisedLocatableCopyRatioRecordToDataLineEncoder());
    }

    /**
     * Generates an instance of {@link DenoisedLocatableCopyRatio} from a {@link DataLine} entry read from a denoised copy
     * ratio file output by {@link PostprocessGermlineCNVCalls}
     */
    private static Function<DataLine, DenoisedLocatableCopyRatio> getDenoisedLocatableCopyRatioRecordFromDataLineDecoder() {
        return dataLine -> {
            try {
                final String contig = dataLine.get(DenoisedLocatableCopyRatioTableColumn.CONTIG);
                final int start = dataLine.getInt(DenoisedLocatableCopyRatioTableColumn.START);
                final int end = dataLine.getInt(DenoisedLocatableCopyRatioTableColumn.END);
                final LinearNonLocatableCopyRatio denoisedCopyRatio = new LinearNonLocatableCopyRatio(dataLine.getDouble(DenoisedLocatableCopyRatioTableColumn.DENOISED_COPY_RATIO));
                return new DenoisedLocatableCopyRatio(new SimpleInterval(contig, start, end), denoisedCopyRatio);
            } catch (final IllegalArgumentException ex) {
                throw new UserException.BadInput(String.format("Validation error occurred on line %d of the denoised copy ratio file : ", dataLine.getLineNumber())
                        + ex.getMessage());
            }
        };
    }

    /**
     * Generates an instance of {@link DataLine} from {@link DenoisedLocatableCopyRatio}
     */
    private static BiConsumer<DenoisedLocatableCopyRatio, DataLine> getDenoisedLocatableCopyRatioRecordToDataLineEncoder() {
        return (denoisedLocatableCopyRatioCopyRatio, dataLine) -> dataLine.append(denoisedLocatableCopyRatioCopyRatio.getContig())
                .append(denoisedLocatableCopyRatioCopyRatio.getStart())
                .append(denoisedLocatableCopyRatioCopyRatio.getEnd())
                .append(denoisedLocatableCopyRatioCopyRatio.getDenoisedCopyRatio().getDenoisedCopyRatio());
    }

}
