package org.broadinstitute.hellbender.tools.copynumber.formats.records;

import htsjdk.samtools.util.Locatable;
import org.broadinstitute.hellbender.utils.SimpleInterval;
import org.broadinstitute.hellbender.utils.Utils;
import org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller;

/**
 * Represents a value of copy ratio in linear space generated by {@link GermlineCNVCaller} with the corresponding interval.
 *
 * @author Andrey Smirnov &lt;asmirnov@broadinstitute.org&gt;
 */
public class LinearCopyRatio implements Locatable {
    private final SimpleInterval interval;
    private final NonLocatableLinearCopyRatio linearCopyRatio;

    public LinearCopyRatio(final SimpleInterval interval, final NonLocatableLinearCopyRatio linearCopyRatio) {
        this.interval = Utils.nonNull(interval, "The interval must be non-null.");
        this.linearCopyRatio = Utils.nonNull(linearCopyRatio, "The copy ratio must be non-null");
    }

    @Override
    public String getContig() {
        return interval.getContig();
    }

    @Override
    public int getStart() {
        return interval.getStart();
    }

    @Override
    public int getEnd() {
        return interval.getEnd();
    }

    public SimpleInterval getInterval() {
        return interval;
    }

    public NonLocatableLinearCopyRatio getLinearCopyRatio() {
        return linearCopyRatio;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        final LinearCopyRatio that = (LinearCopyRatio) o;

        if (!interval.equals(that.interval)) {
            return false;
        }
        return linearCopyRatio.equals(that.linearCopyRatio);

    }

    @Override
    public int hashCode() {
        int result = interval.hashCode();
        result = 31 * result + linearCopyRatio.hashCode();
        return result;
    }
}
